apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator-role
  namespace: default
rules:
  # Permissions pour l'élection de leader (objets Lease)
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  # Permissions pour déclencher le déploiement (patcher l'image)
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  # Permet à l'orchestrateur d'émettre des Events Kubernetes (utile pour le debug/la démo)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: orchestrator
    namespace: default
roleRef:
  kind: Role
  name: orchestrator-role
  apiGroup: rbac.authorization.k8s.io
